namespace BeamNgTerrainPoc.Terrain.StyleConfig;

/// <summary>
/// Root model for osm2world-style.json.
/// Represents the complete OSM2World style configuration with optional BeamNG extensions.
/// Generated by <see cref="StyleConfigGenerator"/> from the downloaded OSM2World style package.
/// </summary>
public class Osm2WorldStyleConfig
{
    /// <summary>Schema identifier for format versioning.</summary>
    public string Schema { get; set; } = "osm2world-style-schema-v1";

    /// <summary>Configuration format version.</summary>
    public int Version { get; set; } = 1;

    /// <summary>Source file this config was generated from (e.g., "standard.properties").</summary>
    public string? GeneratedFrom { get; set; }

    /// <summary>UTC timestamp when this config was generated.</summary>
    public DateTime? GeneratedAt { get; set; }

    /// <summary>Global settings (locale, rendering options, etc.).</summary>
    public StyleGlobalSettings Settings { get; set; } = new();

    /// <summary>
    /// Material definitions keyed by OSM2World material name (e.g., "BRICK", "ROOF_DEFAULT").
    /// Materials with BeamNG extensions have a non-null <see cref="StyleMaterial.Beamng"/> property.
    /// </summary>
    public Dictionary<string, StyleMaterial> Materials { get; set; } = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Model definitions keyed by model name (e.g., "CAR").
    /// Values are lists of model file paths.
    /// </summary>
    public Dictionary<string, List<string>> Models { get; set; } = new(StringComparer.OrdinalIgnoreCase);
}
